/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as LoginAthleteRouteImport } from './routes/login.athlete'
import { Route as LoginCoachRouteImport } from './routes/login.coach'
import { Route as LoginSponsorRouteImport } from './routes/login.sponsor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAthleteRoute = LoginAthleteRouteImport.update({
  id: '/login/athlete',
  path: '/login/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCoachRoute = LoginCoachRouteImport.update({
  id: '/login/coach',
  path: '/login/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSponsorRoute = LoginSponsorRouteImport.update({
  id: '/login/sponsor',
  path: '/login/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roles': typeof RolesRoute
  '/login/athlete': typeof LoginAthleteRoute
  '/login/coach': typeof LoginCoachRoute
  '/login/sponsor': typeof LoginSponsorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roles': typeof RolesRoute
  '/login/athlete': typeof LoginAthleteRoute
  '/login/coach': typeof LoginCoachRoute
  '/login/sponsor': typeof LoginSponsorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roles': typeof RolesRoute
  '/login/athlete': typeof LoginAthleteRoute
  '/login/coach': typeof LoginCoachRoute
  '/login/sponsor': typeof LoginSponsorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/roles' | '/login/athlete' | '/login/coach' | '/login/sponsor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roles' | '/login/athlete' | '/login/coach' | '/login/sponsor'
  id:
    | '__root__'
    | '/'
    | '/roles'
    | '/login/athlete'
    | '/login/coach'
    | '/login/sponsor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RolesRoute: typeof RolesRoute
  LoginAthleteRoute: typeof LoginAthleteRoute
  LoginCoachRoute: typeof LoginCoachRoute
  LoginSponsorRoute: typeof LoginSponsorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/athlete': {
      id: '/login/athlete'
      path: '/login/athlete'
      fullPath: '/login/athlete'
      preLoaderRoute: typeof LoginAthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/coach': {
      id: '/login/coach'
      path: '/login/coach'
      fullPath: '/login/coach'
      preLoaderRoute: typeof LoginCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sponsor': {
      id: '/login/sponsor'
      path: '/login/sponsor'
      fullPath: '/login/sponsor'
      preLoaderRoute: typeof LoginSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RolesRoute: RolesRoute,
  LoginAthleteRoute: LoginAthleteRoute,
  LoginCoachRoute: LoginCoachRoute,
  LoginSponsorRoute: LoginSponsorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
